import React, { useState } from 'react';
import { FileBarChart2, Download } from 'lucide-react';
import { formatDate } from '../utils/format';
const reports = [['attendance', 'Attendance Report', 'Daily check-in, check-out, and status summary.'], ['leave', 'Leave Report', 'Requests, approvals, and pending leave pipeline.'], ['payroll', 'Payroll Report', 'Monthly payroll totals, net pay, and deductions.'], ['employee', 'Employee Report', 'Department distribution and employee lifecycle.']];
export const Reports: React.FC = () => {
  const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const exportCsv = (id: string, name: string) => { const csv = `Report,Date Window\n${name},${formatDate(fromDate)} - ${formatDate(toDate)}`; const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `${id}-report.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><FileBarChart2 className="h-6 w-6 text-indigo-600" /> Reports</h1><p className="mt-1 text-sm text-slate-500">Generate operational reports for HR review.</p></div><div className="panel rounded-xl p-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs text-slate-600">From Date<input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2" /></label><label className="text-xs text-slate-600">To Date<input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2" /></label></div></div><div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{reports.map(([id, name, description]) => <div key={id} className="panel-elevated rounded-xl p-5"><h3 className="text-sm font-semibold text-slate-900">{name}</h3><p className="mt-1 text-xs text-slate-500">{description}</p><button onClick={() => exportCsv(id, name)} className="mt-4 inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white"><Download className="h-3.5 w-3.5" /> Export CSV</button></div>)}</div></div>;
};
